######################################################################
# Automatically generated by qmake (3.0) ?? 3? 28 08:22:53 2016
######################################################################

TEMPLATE = app
TARGET = gotocelldialog
INCLUDEPATH += .

QT += core widgets
QT -= gui

CONFIG += c++11
CONFIG += console
CONFIG -= app_bundle

# Input
HEADERS += \
    ui_gotocelldialog.h \
    gotocelldialog.h
FORMS += gotocelldialog.ui
SOURCES += main.cpp \
    gotocelldialog.cpp
