######################################################################
# Automatically generated by qmake (3.0) ?? 3? 13 15:28:03 2016
######################################################################

TEMPLATE = app
TARGET = hello
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += main.cpp
